Repository ibexa/fieldtype-richtext, pull requests merged in 2022-10, with the labels that each got.

#54 [CI] Removed hardcoded Solr version and switched to one relying on branch-alias
  .github/workflows/ci.yaml
Labels: Ready for MERGE, Ready for review

#53 EZP-30765: Fixed removing custom attributes when switching element
  src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-command.js
Labels: QA approved

#56 IBX-3307: Fixed custom attributes on embeds
  src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-command.js
Labels: Bug
