Repository ibexa/fieldtype-richtext, pull requests merged in 2022-02, with the labels that each got.

#26 IBX-1696: Rebranded Container parameters and Config Resolver namespaces
  src/bundle/DependencyInjection/IbexaFieldTypeRichTextExtension.php
  src/bundle/Resources/config/configuration.yaml
  src/bundle/Resources/config/default_settings.yaml
  src/bundle/Resources/config/fieldtype_services.yaml
  src/bundle/Resources/config/settings/fieldtype_services.yaml
  src/bundle/Resources/config/translation.yaml
  src/bundle/Resources/config/ui/mappers.yaml
  src/lib/RichText/Validator/CustomTagsValidator.php
  tests/bundle/DependencyInjection/IbexaFieldTypeRichTextExtensionTest.php
  tests/integration/Repository/SetupFactory/CoreSetupFactoryTrait.php
  tests/lib/RichText/Validator/CustomTagsValidatorTest.php
  tests/lib/_settings/common.yaml
Labels: Feature

#29 IBX-1832: Removed whitespaces from image embed configuration payload
  src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js
Labels: Bug, QA approved, Ready for MERGE

#34 IBX-2345: Added alignments to images
  src/bundle/Resources/public/js/CKEditor/block-alignment/block-alignment-command.js
  src/bundle/Resources/public/js/CKEditor/block-alignment/block-alignment-editing.js
  src/bundle/Resources/public/js/CKEditor/block-alignment/block-alignment-ui.js
  src/bundle/Resources/public/js/CKEditor/block-alignment/block-alignment.js
  src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
  src/bundle/Resources/public/scss/_general.scss
  src/bundle/Resources/translations/ck_editor.en.xliff
Labels: QA approved
