Repository ibexa/fieldtype-richtext, pull requests merged in 2022-11, with the labels that each got.

#59 IBX-4122: Fixed canceling UDW in link settings
  src/bundle/Resources/public/js/CKEditor/link/link-ui.js
  src/bundle/Resources/public/js/CKEditor/link/ui/link-form-view.js
Labels: Bug, QA approved

#58 IBX-3667: Update icon for embed inline
  src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-ui.js
  src/bundle/Resources/translations/ck_editor.en.xliff
Labels: Bug

#57 IBX-3973: Nontranslatable and disabled fields are not greyed out in content editing UI
  src/bundle/Resources/public/scss/_general.scss
  src/bundle/Resources/public/scss/variables/colors.scss
Labels: Ready for QA
