Repository ibexa/fieldtype-richtext, pull requests merged in 2023-07, with the labels that each got.

#97 IBX-6025: Properties of one custom tag showing in the preview of another
  src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js
Labels: QA approved

#94 IBX-5715: Added validate if anchor value is unique and valid
  src/bundle/Resources/public/js/CKEditor/anchor/anchor-ui.js
  src/bundle/Resources/public/js/CKEditor/anchor/ui/anchor-form-view.js
  src/bundle/Resources/translations/ck_editor.en.xliff
Labels: Bug, QA approved

#92 IBX-5784, IBX-5743: CkEditor toolbar top position fixed
  src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
Labels: QA approved

#99 IBX-6026: Fixed deleting multiple custom tags in once
  src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js
Labels: QA approved

#101 IBX-6151, IBX-6148: Added check if balloon hasView to prevent trying it add again it, corrected logic for countElementsWithSameId
  src/bundle/Resources/public/js/CKEditor/anchor/anchor-ui.js
Labels: Bug, QA approved

#102 IBX-6149: Richtext: Anchor is duplicated when entering newline
  src/bundle/Resources/public/js/CKEditor/anchor/anchor-editing.js
Labels: QA approved

#103 IBX-6162: Add link params to all selected paragraphs
  src/bundle/Resources/public/js/CKEditor/link/link-ui.js
Labels: Ready for QA

#113 Regenerated PHPStan baseline
  phpstan-baseline.neon
Labels: Ready for review

#104 IBX-6071: Handled custom attributes deselection
  src/bundle/Resources/public/js/CKEditor/custom-attributes/ui/custom-attributes-form-view.js
Labels: Improvement, QA approved

#107 IBX-6077: Fixed saving custom classes and attributes on tables in OE
  src/bundle/Resources/richtext/stylesheets/xhtml5/edit/docbook.xsl
  tests/lib/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/009-tableWithCustomClassesAndAttributes.docbook.xml
  tests/lib/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/009-tableWithCustomClassesAndAttributes.xhtml5.edit.xml
  tests/lib/RichText/Validator/DocbookTest.php
Labels: Bug, QA approved
