Repository ibexa/fieldtype-richtext, pull requests merged in 2023-06, with the labels that each got.

#87 IBX-5788: Fixed the `upcast` conversion in image editing
  src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js
Labels: Bug, QA approved

#88 IBX-5757: Fixed custom classes and attributes on headings
  src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-command.js
  src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-editing.js
  src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-ui.js
  src/bundle/Resources/public/js/CKEditor/custom-attributes/helpers/config-helper.js
Labels: Doc needed, QA approved

#86 IBX-5784: CkEditor toolbar overflow fix
  src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
Labels: QA approved

#93 IBX-5950: Fixed last value from one custom class appears in another
  src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-command.js
Labels: QA approved

#91 IBX-5741: Fixed collapsing Custom Tag attribute preview
  src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js
  src/bundle/Resources/public/js/CKEditor/custom-tags/ui/custom-tag-attributes-view.js
Labels: QA approved

#95 IBX-5981: Fixed handling multiple custom classes
  src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-command.js
  src/bundle/Resources/public/js/CKEditor/custom-attributes/ui/custom-attributes-form-view.js
  src/bundle/Resources/public/scss/_balloon-form.scss
Labels: QA approved
