Repository ibexa/fieldtype-richtext, pull requests merged in 2023-03, with the labels that each got.

#75 IBX-5147: [Rich text field type] Closing custom tag before finishing edition causes edition to hover.
  src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js
Labels: QA approved

#76 IBX-4927: Changing custom tag configuration breaks existing Rich Text fields that include this tag
  src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
  src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-editing.js
Labels: QA approved

#78 IBX-2349/5244/5245: Added possibility to add link into embed image
  src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js
  src/bundle/Resources/public/js/CKEditor/link/link-command.js
  src/bundle/Resources/public/js/CKEditor/link/link-ui.js
Labels: QA approved

#80 IBX-5377: Added language of edited content to CKE configuration
  src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
Labels: Bug, QA approved, Ready for MERGE

#79 IBX-5376: Added possibility to change config of CKE
  src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
  src/bundle/Resources/public/scss/_general.scss
Labels: Doc needed, QA approved
