Repository ibexa/fieldtype-richtext, pull requests merged in 2023-10, with the labels that each got.

#128 IBX-6467: Richtext field validation is not styled properly
  src/bundle/Resources/public/scss/_general.scss
  src/bundle/Resources/public/scss/variables/colors.scss
Labels: Bug, QA approved, Ready for MERGE

#132 IBX-6400: Moving images between lines can result in a disapperance of another image
  src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js
Labels: QA approved

#123 IBX-6315: Edit/Preview embedded items
  src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-command.js
  src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-editing.js
  src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-ui.js
  src/bundle/Resources/public/js/CKEditor/embed/content/embed-command.js
  src/bundle/Resources/public/js/CKEditor/embed/content/embed-editing.js
  src/bundle/Resources/public/js/CKEditor/embed/content/embed-ui.js
Labels: Improvement, QA approved
