Repository ibexa/fieldtype-richtext, pull requests merged in 2023-08, with the labels that each got.

#112 IBX-5932: Added max-height for .ck.ck-dropdown__panel
  src/bundle/Resources/public/scss/_general.scss
Labels: Bug, QA approved

#109 IBX-6200: Changed the was custom styles list is diplayed
  src/bundle/Resources/public/js/CKEditor/custom-styles/inline/custom-style-inline-ui.js
Labels: Bug

#115 IBX-5871: Changed check if @xlink:title exists and not empty for a link element
  src/bundle/Resources/richtext/stylesheets/docbook/xhtml5/output/core.xsl
  tests/lib/RichText/Converter/Xslt/_fixtures/docbook/014-link.xml
  tests/lib/RichText/Converter/Xslt/_fixtures/xhtml5/edit/014-link.xml
  tests/lib/RichText/Converter/Xslt/_fixtures/xhtml5/output/014-link.xml
Labels: Bug, QA approved, Ready for review

#118 IBX-6217: Forced `RichText\Renderer`to utilize `PermissionResolver` instead of `AuthorizationChecker`
  phpstan-baseline.neon
  src/bundle/Resources/config/fieldtype_services.yaml
  src/lib/RichText/Renderer.php
  tests/lib/RichText/RendererTest.php
Labels: Improvement, QA approved, Ready for QA

#119 IBX-6310: Separated text extraction logic from SearchField class
  phpstan-baseline.neon
  src/bundle/Resources/config/settings/fieldtype_services.yaml
  src/bundle/Resources/config/settings/fieldtypes.yaml
  src/bundle/Resources/config/settings/indexable_fieldtypes.yaml
  src/contracts/RichText/TextExtractorInterface.php
  src/lib/FieldType/RichText/SearchField.php
  src/lib/FieldType/RichText/Type.php
  src/lib/RichText/TextExtractor/FullTextExtractor.php
  src/lib/RichText/TextExtractor/ShortTextExtractor.php
  tests/lib/FieldType/RichText/SearchFieldTest.php
  tests/lib/FieldType/RichTextTest.php
  tests/lib/RichText/TextExtractor/BaseTest.php
  tests/lib/RichText/TextExtractor/FullTextExtractorTest.php
  tests/lib/RichText/TextExtractor/ShortTextExtractorTest.php
Labels: Improvement, QA approved

#117 IBX-6078: Added Revert to saved button
  src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-ui.js
  src/bundle/Resources/public/js/CKEditor/custom-attributes/ui/custom-attributes-form-view.js
  src/bundle/Resources/public/scss/_balloon-form.scss
Labels: Bug, QA approved

#121 IBX-6352: Blocked image upload when moving it inside RTE
  src/bundle/Resources/public/js/CKEditor/upload-image/upload-image-editing.js
Labels: Bug, QA approved

#124 IBX-6354: Set z-index for .ck-toolbar-container and .ck-balloon-panel_with-arrow
  src/bundle/Resources/public/scss/_balloon-form.scss
Labels: Bug, QA approved

#125 IBX-6313: Fixed anchor in empty paragraph
  src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
Labels: QA approved, Ready for MERGE
