Repository ibexa/fieldtype-richtext, pull requests merged in 2024-08, with the labels that each got.

#174 IBX-8337: Can't add Custom classes and attributes for TR element with multiple line
  src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-command.js
Labels: QA approved

#173 IBX-7694: Richtext custom tag attributes don't have effect on existing tags
  src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js
Labels: QA approved

#172 IBX-8138: [Rector] Applied rules from Symfony 5 Rector set lists
  src/bundle/DependencyInjection/Configuration.php
  src/bundle/DependencyInjection/IbexaFieldTypeRichTextExtension.php
  src/bundle/IbexaFieldTypeRichTextBundle.php
  src/lib/FieldType/RichText/Value.php
  src/lib/Form/Type/RichTextFieldType.php
Labels: Ready for MERGE, Ready for review

#171 IBX-8502: Added unsupported locale fallback
  src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
Labels: QA approved, Ready for review

#179 IBX-8150: Added option to enable attributes types
  src/bundle/Resources/encore/ez.webpack.custom.config.js
  src/bundle/Resources/public/js/CKEditor/common/input-number/input-number-view.js
  src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js
  src/bundle/Resources/public/js/CKEditor/custom-tags/ui/custom-tag-attributes-view.js
  src/bundle/Resources/public/js/CKEditor/custom-tags/ui/custom-tag-form-view.js
Labels: QA approved
