Repository ibexa/fieldtype-richtext, pull requests merged in 2024-06, with the labels that each got.

#162 Added translation extractor for custom tags
  .gitignore
  src/bundle/DependencyInjection/IbexaFieldTypeRichTextExtension.php
  src/bundle/Resources/config/translation.yaml
  src/bundle/Resources/translations/custom_tags.en.xliff
  src/lib/Translation/Extractor/ChoiceAttributeExtractor.php
  src/lib/Translation/Extractor/CustomTagExtractor.php
  src/lib/Translation/Extractor/MessageCatalogueBuilder.php
  src/lib/Translation/Extractor/OnlineEditorCustomAttributesExtractor.php
  tests/integration/IbexaTestKernel.php
  tests/integration/Resources/override.yaml
Labels: QA approved

#166 IBX-8363: Corrected namespace for RichTextFieldValueConverterTest and added return types
  phpstan-baseline.neon
  tests/lib/Persistence/Legacy/Tests/Content/FieldValue/Converter/RichTextFieldValueConverterTest.php
Labels: Bug, Ready for review

#164 IBX-8352: Handled disabled distraction-free mode
  src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
Labels: Bug, QA approved
