Repository ibexa/fieldtype-richtext, pull requests merged in 2024-07, with the labels that each got.

#165 IBX-8340: RichText: Not possible to create a link to a custom route
  src/bundle/Resources/public/js/CKEditor/link/ui/link-form-view.js
Labels: QA approved

#169 IBX-8434: Added ProviderConfiguratorInterface to allow configuration post-processing
  phpstan-baseline.neon
  src/bundle/Resources/config/configuration.yaml
  src/bundle/Resources/config/ui/mappers.yaml
  src/contracts/Configuration/ProviderConfiguratorInterface.php
  src/lib/Configuration/Provider/ConfigurableProvider.php
  src/lib/Configuration/Provider/CustomTag.php
  src/lib/Configuration/UI/Mapper/CustomTag.php
  src/lib/Configuration/UI/Mapper/CustomTag/AttributeMapper.php
  src/lib/Configuration/UI/Mapper/CustomTag/ChoiceAttributeMapper.php
  tests/lib/Configuration/Provider/ConfigurableProviderTest.php
Labels: Doc needed, Ready for review

#167 IBX-8150: Added option to enable attributes types
  src/bundle/DependencyInjection/Configuration.php
  tests/bundle/DependencyInjection/Configuration/ConfigurationTest.php
  tests/bundle/DependencyInjection/Fixtures/custom_tags/output/000-attribute-type-number.yaml
  tests/bundle/DependencyInjection/Fixtures/custom_tags/output/001-attribute-type-string.yaml
  tests/bundle/DependencyInjection/Fixtures/custom_tags/output/002-attribute-type-boolean.yaml
  tests/bundle/DependencyInjection/Fixtures/custom_tags/output/003-attribute-type-choice.yaml
  tests/bundle/DependencyInjection/Fixtures/custom_tags/output/004-attribute-type-link.yaml
Labels: QA approved

#168 IBX-8342: Fixed creating tables in Online Editor
  src/bundle/Resources/public/scss/_balloon-form.scss
Labels: Bug, QA approved, Ready for review
