Repository ibexa/fieldtype-richtext, pull requests merged in 2025-07, with the labels that each got.

#242 IBX-10087: Left-aligned image overlaps with blocks in Richtext field
  src/bundle/Resources/public/scss/_general.scss
Labels: QA approved

#249 Adapted `RichTextProcessor`'s methods to `ibexa/rest` strict types
  src/lib/REST/FieldTypeProcessor/RichTextProcessor.php
Labels: Improvement, Ready for review

#251 IBX-10173: Extract webpack files from root dir
  package.json
  src/bundle/Resources/encore/ibexa.webpack.custom.config.js
  src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js
Labels: Ready for review

#253 IBX-10262: Renamed and refactored `CustomTagsValidator` to support both Custom Tags and Styles
  phpstan-baseline.neon
  src/bundle/Resources/config/settings/fieldtype_services.yaml
  src/lib/RichText/Validator/CustomTagsValidator.php
  src/lib/RichText/Validator/CustomTemplateValidator.php
  tests/lib/RichText/Validator/CustomTemplateValidatorTest.php
  tests/lib/_settings/common.yaml
Labels: Ready for review

#256 IBX-10268: Fixed custom tag upcast
  src/bundle/Resources/public/js/CKEditor/custom-tags/inline-custom-tag/inline-custom-tag-editing.js
Labels: QA approved

#258 [Tests] Fixed xml nodes' ids after Libxml update
  tests/lib/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/008-anchor.docbook.xml
  tests/lib/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/010-duplicatedIds.docbook.xml
Labels: Ready for review, Tests update

#247 IBX-10068: Unified list style for nested lists
  src/bundle/Resources/public/scss/_general.scss
Labels: QA approved, Ready for QA
