Repository ibexa/fieldtype-richtext, pull requests merged in 2025-05, with the labels that each got.

#227 IBX-9926: [Collaboration] Users list for CKEditor
  .github/workflows/frontend-ci.yaml
  phpstan-baseline.neon
  src/bundle/Resources/public/scss/variables/colors.scss
  src/bundle/Resources/public/scss/variables/vars.scss
Labels: QA approved

#217 IBX-8471: Upgraded codebase to Symfony 7
  composer.json
  phpstan-baseline.neon
  phpstan.neon
  src/bundle/IbexaFieldTypeRichTextBundle.php
  src/lib/FieldType/RichText/RichTextStorage.php
  src/lib/FieldType/RichText/RichTextStorage/Gateway.php
  src/lib/FieldType/RichText/RichTextStorage/Gateway/DoctrineStorage.php
  src/lib/Form/DataTransformer/RichTextValueTransformer.php
  src/lib/Persistence/Legacy/MigrateRichTextNamespaces/Gateway/DoctrineDatabase.php
  tests/integration/Repository/RichTextFieldTypeIntegrationTest.php
  tests/integration/Repository/SetupFactory/LegacySetupFactory.php
Labels: Ready for SF7

#233 Added ibexa/twig-components to require-dev
  composer.json
  tests/integration/IbexaTestKernel.php
Labels: Ready for review
