Repository ibexa/fieldtype-richtext, pull requests merged in 2025-02, with the labels that each got.

#201 IBX-9326: The image link with a class is producing an error
  src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js
Labels: QA approved

#203 IBX-9392: Richtext editor menu is hidden below "ibexa-edit-header"
  src/bundle/Resources/public/scss/_balloon-form.scss
Labels: Bug, QA approved, Ready for MERGE

#205 IBX-9513: Fixed obsolete `ibexa_content` Controller references
  src/bundle/Resources/views/RichText/embed/content.html.twig
  src/bundle/Resources/views/RichText/embed/content_inline.html.twig
  src/bundle/Resources/views/RichText/embed/location.html.twig
  src/bundle/Resources/views/RichText/embed/location_inline.html.twig
Labels: QA approved

#200 IBX-9298: multiple Custom CSS - no visual indication of selected items
  src/bundle/Resources/public/js/CKEditor/common/chips-button-view/chips-button-view.js
  src/bundle/Resources/public/js/CKEditor/common/multivalue-dropdown/utils.js
  src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-ui.js
  src/bundle/Resources/public/js/CKEditor/custom-attributes/ui/custom-attributes-form-view.js
  src/bundle/Resources/public/js/CKEditor/link/ui/link-form-view.js
  src/bundle/Resources/public/scss/_balloon-form.scss
  src/bundle/Resources/public/scss/_custom-panel.scss
Labels: QA approved

#204 IBX-9509: Revert deprecation of custom attributes labels extractor
  src/bundle/Resources/config/translation.yaml
  src/lib/Translation/Extractor/OnlineEditorCustomAttributesExtractor.php
Labels: QA approved

#206 IBX-8849: Texts "Title" and "Undefined" in Landing page Block rich text link are bad aligned
  src/bundle/Resources/public/js/CKEditor/link/link-ui.js
Labels: QA approved

#209 Removing ez_richtext_config deprecation
  src/bundle/Templating/Twig/Extension/RichTextConfigurationExtension.php
Labels: Ready for review
